import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import 'simplebar-react/dist/simplebar.min.css';
import styles from "./layout.module.scss";

import CalendarContextProvider from "@/context";
import { getDateString } from "@/utils/dateString";
import { getNextDates } from "@/utils/days";
import MiniCalendar from "@/components/MiniCalendar";
import Backlog from "@/components/Backlog";
import ScrollSyncContextProvider from "@/scrollSync/ScrollSyncContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const today = new Date();
    const todayDate = getDateString(today.getFullYear(), today.getMonth() + 1, today.getDate());

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CalendarContextProvider
                    initialSelectedDate={todayDate}
                    initialDateRange={getNextDates(todayDate, 5)}
                >
                    <div className={styles.layout}>
                        <div className={styles.side_panel}>
                            <MiniCalendar />
                            <Backlog />
                        </div>
                        <ScrollSyncContextProvider>
                            <div className={styles.main_content}>{children}</div>      
                        </ScrollSyncContextProvider>
                    </div>
                </CalendarContextProvider>
            </body>
        </html>
    );
}
