import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import 'simplebar-react/dist/simplebar.min.css';
import styles from "./layout.module.scss";

import CalendarContextProvider from "@/context";
import { getDateString, getDateStringFromDate, todayUtc } from "@/utils/date";
import { getNextDates } from "@/utils/days";
import MiniCalendar from "@/components/AppCalendar";
import Backlog from "@/components/Backlog";
import ScrollSyncContextProvider from "@/scrollSync/ScrollSyncContext";
import TaskConextProvider from "@/taskContext";
import { ContextMenuProvider } from "@/components/_layout/ContextMenu/ContextMenuContext";
import { ContextMenuRenderer } from "@/components/_layout/ContextMenu/ContextMenuRenderer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CalendarContextProvider
                    initialSelectedDate={today}
                    initialDateRange={getNextDates(today, 5)}
                >
                    <TaskConextProvider>
                        <ContextMenuProvider>
                            <div className={styles.layout}>
                                <div className={styles.side_panel}>
                                    <MiniCalendar />
                                    <Backlog />
                                </div>
                                <ScrollSyncContextProvider>
                                    <div className={styles.main_content}>{children}</div>      
                                </ScrollSyncContextProvider>
                            </div>
                            <ContextMenuRenderer/>
                        </ContextMenuProvider>
                    </TaskConextProvider>
                </CalendarContextProvider>
            </body>
        </html>
    );
}
