import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import 'simplebar-react/dist/simplebar.min.css';
import styles from "./layout.module.scss";

import CalendarContextProvider from "@/context";
import { getNextDates } from "@/utils/days";
import AppCalendar from "@/components/SidePanel/AppCalendar";
import Backlog from "@/components/SidePanel/Backlog";
import ScrollSyncContextProvider from "@/scrollSync/ScrollSyncContext";
import TaskConextProvider from "@/taskContext";
import { ContextMenuProvider } from "@/components/_layout/ContextMenu/ContextMenuContext";
import { ContextMenuRenderer } from "@/components/_layout/ContextMenu/ContextMenuRenderer";
import TimeBlockContextProvider from "@/timeBlockContext";
import SidePanel from "@/components/SidePanel";
import TimerProvider from "@/timerContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CalendarContextProvider
                    initialSelectedDate={today}
                    initialDateRange={getNextDates(today, 5)}
                >
                    <TimerProvider>
                        <TaskConextProvider>
                            <ContextMenuProvider>
                                <TimeBlockContextProvider>
                                    <div className={styles.layout}>
                                        <ScrollSyncContextProvider>
                                            <SidePanel />
                                            <div className={styles.main_content}>{children}</div>      
                                        </ScrollSyncContextProvider>
                                    </div>
                                </TimeBlockContextProvider>
                                <ContextMenuRenderer/>
                            </ContextMenuProvider>
                        </TaskConextProvider>
                    </TimerProvider>
                </CalendarContextProvider>
            </body>
        </html>
    );
}
